python train.py --task_name Tacred \
    --num_k 5 \
    --num_gen 5 \
    --mixup \
    --SAM \
    --base_optimizer Adam \
    --sam_optimizer SAM \
    --rho 0.05 \
    --decay 0 \
    --distill \
    --distill_type OFA \
    --distill_alpha 0.25